/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.3/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.9.0"

    kotlin("kapt") version "1.9.0"

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    maven {
        url=uri("https://jitpack.io")
    }
}

dependencies {
    api("org.pf4j:pf4j:${project.properties["pf4jVersion"]}")
    api("com.badlogicgames.gdx:gdx:${project.properties["libgdxVersion"]}")
    kapt("org.pf4j:pf4j:${project.properties["pf4jVersion"]}")

    api(project(":runtime"))

    // TODO: Change to JamesTKhan's link after this branch merged
    implementation("com.github.Dgzt.Mundus:plugin-api:${project.properties["mundusVersion"]}")
    implementation("com.github.Dgzt.Mundus:editor-commons:${project.properties["mundusVersion"]}")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(8))
    }
}

tasks.withType<Jar> {
    dependsOn(":runtime:jar")

    archiveFileName.set("racast-plugin.jar")

    // Otherwise you'll get a "No main manifest attribute" error
    manifest {
        attributes["Plugin-Class"]= "com.github.dgzt.mundus.plugin.recast.MundusRecastPlugin"
        attributes["Plugin-Id"] = "recast-plugin"
        attributes["Plugin-Provider"] = "Tibor Zsuro (Dgzt)"
        attributes["Plugin-Version"] = "0.0.1"
    }

    // Include runtime in jar file
    val dependencies = configurations
        .runtimeClasspath
        .get()
        .filter {
            it.name.equals("runtime.jar") ||
            it.name.equals("gdx-recast-${project.properties["gdxRecastVersion"]}.jar") ||
            it.name.equals("recast-gwt_migration_antz-SNAPSHOT.jar") ||
            it.name.equals("detour-gwt_migration_antz-SNAPSHOT.jar")
        }
        .map(::zipTree)
    from(dependencies)
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
